services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "shortenerodmen"
      POSTGRES_PASSWORD: "shortenerodmen"
      POSTGRES_DB: "shortener"
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql