BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS urls (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    short VARCHAR(200) NOT NULL,
    long VARCHAR(200) NOT NULL,
    user_id VARCHAR(200) NOT NULL DEFAULT 'NULL_USER',
    is_deleted BOOLEAN DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_long_url ON urls (long);

CREATE UNIQUE INDEX IF NOT EXISTS idx_short_is_not_deleted ON urls (short) WHERE is_deleted = FALSE;

COMMIT;