BEGIN TRANSACTION;

SET ROLE TO shortenerodmen;

SELECT current_user;

CREATE TABLE IF NOT EXISTS urls (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    short VARCHAR(200) NOT NULL,
    long VARCHAR(200) NOT NULL
);

COMMIT;