BEGIN TRANSACTION;

ALTER TABLE urls
ADD COLUMN user_id VARCHAR(200) NOT NULL DEFAULT 'NULL_USER',
ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_short_is_not_deleted ON urls (short) WHERE is_deleted = FALSE;
COMMIT;