SET ROLE TO odmen;

SELECT current_user;

CREATE TABLE IF NOT EXISTS urls (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    short VARCHAR(200) NOT NULL UNIQUE,
    long VARCHAR(200) NOT NULL,
    user_id VARCHAR(200) NOT NULL
);