// Package metadata shares info about the application, such as commit, Version and build time.
package main

import (
	"fmt"
	"log"
	"os"
	"time"
)

func main() {
	const filename = "gen_metadata.go"
	Version := os.Getenv("BUILD_VERSION")
	if Version == "" {
		Version = "N/A"
	}
	commit := os.Getenv("BUILD_COMMIT")
	if commit == "" {
		commit = "N/A"
	}
	Date := time.Now().Format(time.DateTime)

	code := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.
package main
var (
	BuildVersion = "%s"
	BuildDate    = "%s"
	BuildCommit  = "%s"
)
`, Version, Date, commit)

	file, err := os.Create(filename)
	if err != nil {
		log.Printf("failed to create file: %s, %+v\n", filename, err)
		return
	}
	defer func() {
		if err = file.Close(); err != nil {
			log.Printf("failed to close file: %s, %+v\n", filename, err)
		}
	}()

	if _, err = file.WriteString(code); err != nil {
		log.Printf("failed to write into the file: %s, %+v\n", filename, err)
	}
}
